Module is experimental. 
config file is: /projects/p30771/dlc_analysis/Test_dlc-Santiago-2020-10-06/config.yaml
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
/projects/p30771/dlc_analysis/Test_dlc-Santiago-2020-10-06/training-datasets/iteration-0/UnaugmentedDataSet_Test_dlcOct6  already exists!
It appears that the images were labeled on a Windows system, but you are currently trying to create a training set on a Unix system. 
 In this case the paths should be converted. Do you want to proceed with the conversion?
yes/noTraceback (most recent call last):
  File "run_dlc_openfield.py", line 13, in <module>
    deeplabcut.create_training_dataset(path_config_file)
  File "/home/jma819/DeepLabCut/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 904, in create_training_dataset
    cfg, Path(os.path.join(project_path, trainingsetfolder)), windows2linux
  File "/home/jma819/DeepLabCut/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 646, in merge_annotateddatasets
    askuser = input("yes/no")
EOFError: EOF when reading a line
