Module is experimental. 
config file is: /projects/p30771/dlc_analysis/Open_Field_v2-JJM-2020-01-27/
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jma819/.conda/envs/tensorflow-gpu-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "/home/jma819/DeepLabCut/deeplabcut/utils/auxiliaryfunctions.py", line 116, in read_config
    with open(path, 'r') as f:
IsADirectoryError: [Errno 21] Is a directory: '/projects/p30771/dlc_analysis/Open_Field_v2-JJM-2020-01-27'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dlc_evaluate_network.py", line 20, in <module>
    deeplabcut.evaluate_network(path_config_file, plotting=True)
  File "/home/jma819/DeepLabCut/deeplabcut/pose_estimation_tensorflow/evaluate.py", line 248, in evaluate_network
    cfg = auxiliaryfunctions.read_config(config)
  File "/home/jma819/DeepLabCut/deeplabcut/utils/auxiliaryfunctions.py", line 119, in read_config
    if err.args[2] == "could not determine a constructor for the tag '!!python/tuple'":
IndexError: tuple index out of range
